<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<DebugType>None</DebugType>

		<!-- bundle everything into a single executable -->
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>MercuryLauncher</RootNamespace>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="Program.fs" />
	</ItemGroup>
</Project>
